@echo off
SET "DATABASE_URL=postgresql://neondb_owner:npg_S0JXVWY5gIyl@ep-misty-block-anoyhjbr-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
echo Generating Prisma Client...
npx prisma generate
echo Pushing schema to database...
npx prisma db push
